root_folder: /data/riksdagen_corpus_data
data_folder: /data/riksdagen_corpus_data
version: v1.4.1

corpus:
  version: v1.4.1
  folder: /data/riksdagen_corpus_data/riksdagen-records/data
  pattern: "**/prot-*-*.xml"
  github:
    user: swerik-project
    repository: riksdagen-records
    path: data

fakes:
  folder: tests/test_data/fakes/v1.4.1/riksdagen-records
  expected_folder: tests/test_data/fakes/version/v1.4.1/expected

metadata:
  version: v1.1.3
  folder: /data/riksdagen_corpus_data/metadata/v1.1.3
  database:
    type: pyriksprot.metadata.database.SqliteDatabase
    options:
      filename: /data/riksdagen_corpus_data/metadata/riksprot_metadata.v1.1.3.db
    # type: pyriksprot.metadata.database.PostgresDatabase
    # options:
    #   # filename: /data/riksdagen_corpus_data/metadata/riksprot_metadata.v1.1.3.db
    #   host: ...
    #   database: riksprot_metadata_v1_1_0
    #   user: ...
    #   password: xyz
    #   port: 5433
  github:
    user: swerik-project
    repository: riksdagen-persons
    path: data
    url: https://github.com/swerik-project/riksdagen-records.git

tagged_frames:
  folder: /data/riksdagen_corpus_data/v1.4.1/tagged_frames
  file_pattern: prot-*.zip
  pattern: /data/riksdagen_corpus_data/v1.4.1/tagged_frames/**/prot-*.zip

tagged_speeches:
  folder: /data/riksdagen_corpus_data/v1.4.1/tagged_frames_speeches.feather

dehyphen:
  folder: /data/riksdagen_corpus_data/v1.4.1/dehyphen
  tf_filename: /data/riksdagen_corpus_data/v1.4.1/dehyphen/word-frequencies.pkl

tagger:
  module: pyriksprot_tagger.taggers.stanza_tagger
  stanza_datadir: /data/sparv/models/stanza
  preprocessors: dedent,dehyphen,strip,pretokenize
  lang: "sv"
  processors: tokenize,lemma,pos
  tokenize_pretokenized: true
  tokenize_no_ssplit: true
  use_gpu: true
  num_threads: 1

global:
  corpus:
    folder: /data/riksdagen_corpus_data/riksdagen-records/data
  metadata:
    folder: /data/riksdagen_corpus_data/riksdagen-persons/data
